name: hodgeclean
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy>=1.26.0
  - scipy>=1.13.0
  - pandas>=2.2.0
  - sympy>=1.12
  - matplotlib>=3.8.0
  - jsonschema>=4.21.0
  - notebook>=7.1.0
  - pip
  - pip:
      - mpmath>=1.3.0
